/**
 * Predefined headers for AMS format files
 * These headers will be assigned to columns in the order they appear
 */
export const amsHeaders: string[] = [
  "Total Due", // TOTAL_DUE (0)
  "Current Date", // CURRENT_DATE (1)
  "Merchant Name", // MERCHANT_NAME (2)
  "Total Sales Tax", // TOTAL_SALES_TAX (3)
  "Invoice Date", // INVOICE_DATE (4)
  "Display Account Number", // DISPLAY_ACCOUNT_NUMBER (5)
  "Plant State", // PLANT_STATE (6)
  "Plant ZIP", // PLANT_ZIP (7)
  "Merchant MIN", // MERCHANT_MIN (8)
  "Ship From ZIP", // SHIP_FROM_ZIP (9)
  "Ship To ZIP", // SHIP_TO_ZIP (10)
  "Invoice Number", // INVOICE_NUMBER (11)
  "Order Number", // ORDER_NUMBER (12)
  "Part Number", // PART_NUMBER (13)
  "Commodity Code", // COMMODITY_CODE (14)
  "Description", // DESC (15)
  "Quantity Ordered", // QTY_ORDER_COL (16)
  "Unit of Measure", // UOM_COL (17)
  "Net Amount", // NET_AMOUNT_COL (18)
  "Freight", // FREIGHT (19)
  "Duty Amount", // DUTY_AMT (20)
  "Account Number", // ACCOUNT_NUMBER (21)
  "Billing Address Line 1", // BILLING_ADDRESS_1 (22)
  "Billing Address Line 2", // BILLING_ADDRESS_2 (23)
  "Billing Address Line 3", // BILLING_ADDRESS_3 (24)
  "Billing Address Line 4", // BILLING_ADDRESS_4 (25)
  "Billing City", // BILLING_ADDRESS_CITY (26)
  "Billing State", // BILLING_ADDRESS_STATE (27)
  "Billing ZIP", // BILLING_ADDRESS_ZIP (28)
  "Billing Country", // BILLING_COUNTRY (29)
  "Shipping Country Code", // SHIPPING_CCODE (30)
  "Order Date", // ORDER_DATE (31)
  "Line", // LINE_COL (32)
  "Product", // PRODUCT_COL (33)
  "Discount Amount", // DISCOUNT_AMOUNT (34)
  "Sales Tax", // SALES_TAX (35)
  "Total Discount Amount", // TOTAL_DISCOUNT_AMOUNT (36)
]; 